---
title: "MA 615 Final Project"
author: "Jiahao Liu"
date: "2022-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
stop_times_11_21 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times0.txt")
stop_times_12_21 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times1.txt")
stop_times_01_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times2.txt")
stop_times_02_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times3.txt")
stop_times_03_22_1 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times4_1.txt")
stop_times_03_22_2 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times4_2.txt")
stop_times_03_22_3 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times4_3.txt")
stop_times_03_22 <- rbind(stop_times_03_22_1, stop_times_03_22_2, stop_times_03_22_3)
stop_times_04_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times5.txt")
stop_times_05_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times6.txt")
stop_times_06_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times7.txt")
stop_times_07_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times8.txt")
stop_times_08_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times9.txt")
stop_times_09_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times10.txt")
stop_times_10_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/stop_times11.txt")

stop_time <- rbind(stop_times_11_21,stop_times_12_21,stop_times_01_22,stop_times_02_22,stop_times_03_22,stop_times_04_22,stop_times_05_22,stop_times_06_22,stop_times_07_22,stop_times_08_22,stop_times_09_22,stop_times_10_22)
```

## Calendar
```{r}
calendar_11_21 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes0.txt")
calendar_12_21 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes1.txt")
calendar_01_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes2.txt")
calendar_02_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes3.txt")
calendar_03_22_1 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes4_1.txt")
calendar_03_22_2 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes4_2.txt")
calendar_03_22_3 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes4_3.txt")
calendar_03_22 <- rbind(calendar_03_22_1, calendar_03_22_2, calendar_03_22_3)
calendar_04_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes5.txt")
calendar_05_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes6.txt")
calendar_06_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes7.txt")
calendar_07_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes8.txt")
calendar_08_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes9.txt")
calendar_09_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes10.txt")
calendar_10_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes11.txt")

calendar <- rbind(calendar_11_21,calendar_12_21,calendar_01_22,calendar_02_22,calendar_03_22,calendar_04_22,calendar_05_22,calendar_06_22,calendar_07_22,calendar_08_22,calendar_09_22,calendar_10_22)
```


```{r,fig.height=5, fig.width=7}
library(fmsb)
#unique(calendar$rating_description)
calendar_rate <- data.frame(calendar$service_schedule_typicality,calendar$rating_description)

calendar_rate_1 <- calendar_rate %>%
  filter(calendar.rating_description == 'Fall')
#count(calendar_rate_1,calendar.service_schedule_typicality)

calendar_rate_2 <- calendar_rate %>%
  filter(calendar.rating_description == 'Spring')
#count(calendar_rate_2,calendar.service_schedule_typicality)

calendar_rate_3 <- calendar_rate %>%
  filter(calendar.rating_description == 'Summer')
#count(calendar_rate_3,calendar.service_schedule_typicality)

calendar_rate_4 <- calendar_rate %>%
  filter(calendar.rating_description == 'Winter')
#count(calendar_rate_4,calendar.service_schedule_typicality)

calendar_rate_5 <- calendar_rate %>%
  filter(calendar.rating_description == 'Summer/Fall')
#count(calendar_rate_5,calendar.service_schedule_typicality)

calendar_rate_6 <- calendar_rate %>%
  filter(calendar.rating_description == 'Fall/Winter')
#count(calendar_rate_6,calendar.service_schedule_typicality)

calendar_rate_7 <- calendar_rate %>%
  filter(calendar.rating_description == 'Spring/Summer')
#count(calendar_rate_7,calendar.service_schedule_typicality)

season_rate <- as.data.frame(matrix( c(132,96,351,169,112,0,18,0,0,0,4,0,0,0,5,13,6,9,0,0,0,58,28,210,45,96,19,16,0,8,9,0,0,0,0) , ncol=5))
colnames(season_rate) <- c("Typicality-1", "Typicality-2", "Typicality-3", "Typicality-4", "Typicality-5")
rownames(season_rate) <- c("Spring", "Summer" , "Fall" , "Winter" , "Spring/Summer", "Summer/Fall", "Fall/Winter")

library(RColorBrewer)
coul <- brewer.pal(7, "Set2")
colors_border <- coul
library(scales)
colors_in <- alpha(coul,0.4)

radarchart(season_rate,axistype=0, maxmin=F,pcol = colors_border, pfcol=colors_in, plwd=2.5, plty=1,vlcex=0.8,cglcol="grey", cglty=1)
legend(x = 'topright', legend = rownames(season_rate), bty = "n", pch=15 , col=colors_in , text.col = "grey", cex=1, pt.cex=2.5)
```

```{r,fig.height=5, fig.width=7}
week_rate <- data.frame(
  schedule = calendar$service_schedule_type, 
  typicality = calendar$service_schedule_typicality)

week_rate_1 <- week_rate %>%
  filter(schedule == 'Weekday')
#count(week_rate_1,typicality)

week_rate_2 <- week_rate %>%
  filter(schedule == 'Saturday')
#count(week_rate_2,typicality)

week_rate_3 <- week_rate %>%
  filter(schedule == 'Sunday')
#count(week_rate_3,typicality)


week_rate_new <- as.data.frame(matrix( c(366,231,281,4,0,0,5,4,24,146,162,164,17,0,0) , ncol=5))
colnames(week_rate_new) <- c("Typicality-1", "Typicality-2", "Typicality-3", "Typicality-4", "Typicality-5")
rownames(week_rate_new) <- c("Weekday", "Saturday" , "Sunday")

library(RColorBrewer)
coul <- brewer.pal(3, "Set3")
colors_border <- coul
library(scales)
colors_in <- alpha(coul,0.4)

radarchart(week_rate_new,axistype=0, maxmin=F,pcol = colors_border, pfcol=colors_in, plwd=2.5, plty=1,vlcex=0.8,cglcol="grey", cglty=1)
legend(x = 'topright', legend = rownames(week_rate_new), bty = "n", pch=15 , col=colors_in , text.col = "grey", cex=1, pt.cex=2.5)
```

## Route Patterns
```{r}
route_11_21 <- read.csv("C:/Users/Jiahao Liu/Desktop/route_patterns0.txt")
route_12_21 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes1.txt")
route_01_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes2.txt")
route_02_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes3.txt")
route_03_22_1 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes4_1.txt")
route_03_22_2 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes4_2.txt")
route_03_22_3 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes4_3.txt")
route_03_22 <- rbind(calendar_03_22_1, calendar_03_22_2, calendar_03_22_3)
route_04_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes5.txt")
route_05_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes6.txt")
route_06_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes7.txt")
route_07_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes8.txt")
route_08_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes9.txt")
route_09_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes10.txt")
route_10_22 <- read.csv("C:/Users/Jiahao Liu/Desktop/calendar_attributes11.txt")

```

          